### ISSUE TITLE
Display full addresses on `sign` flow

### ISSUE THREAD

**Issue by arobsn** [tesseract-one/ledger-app-ergo#10]
From Ledger team:
> On Ledger Nano S, on a `send` flow, the receiving address is truncated like `9zdf21...13ez1z`, it would be better to display the whole address, even if it adds more screens to go through.

**Comment by ypopovych** [comment]
have you checked the latest version from this repo? I think I already implemented it

**Comment by ypopovych** [comment]
https://github.com/tesseract-one/ledger-app-ergo/commit/a450a3422885e7dd9e40af451083e2304e7d0ff8
