### ISSUE TITLE
Reduce the amount of confirmations on `sign` flow

### ISSUE THREAD

**Issue by arobsn** [tesseract-one/ledger-app-ergo#11]
From Ledger team:
> As I previously mentioned, we are trying to unify as much as possible the flow between all the embedded apps we have, especially since Ledger Stax has been announced as new Ledger device. In this direction, we push developers to adopt a Send flow (in particular), where the user has only one chunk to `Approve` instead of multiple ones. We also want to reduce the number of screens to the minimum which of course guarantees security. That being said, I know every blockchain has its own constraints, that's why I don't know exactly how far you can push this.

## Change confirmations
1. **Only require change confirmations if the change index is greater than 19**, not the ideal solution but will improve the UX for 99% of the users. Wallets usually do address balance checks by querying chunks of 20 addresses until the last used one plus 20 (e.g. Bob has 0, 1, and 2 used addresses, so the wallet will query until index 22).
2. **If the change index is greater than 19, only confirm once per change path.** To mitigate the effects of the 20 token limit per transaction, Nautilus isolates distinct tokens in multiple change boxes, one per distinct token, which will make further transactions more efficient and less prone to fail doe this limitation. It's working really good, but on the Ledger App side, the UX is not so good since the user needs to confirm all the change boxes produced. Let's say we have a TX with 10 distinct tokens in the inputs, even if the user is sending a single one, he still needs to confirm 10 or 9 change boxes.

## Signing confirmations
Currently, we are asking for signing path confirmation at the beginning and the end of the signing flow. It would be probably good to remove the first confirmation and replace it with "Start signing" which can be accepted by the user pressing the two buttons at the same time.

**Comment by ypopovych** [comment]
implemented in #13
