### ISSUE TITLE
Display the recipient address when signing transactions

### ISSUE THREAD

**Issue by squigglemiggles** [tesseract-one/ledger-app-ergo#5]
I understand there is limited space to play with on ledger nano s and as a result a critical security feature (in my view) has been ommited.

When signing transactions the recipient address is not displayed on the ledger device. I feel this is important as a way to verify I'm sending the tokens to the right address. 

In addition, what is stopping a malicious dapp (or wallet) to provide ledger support, but when signing send the tokens to a different address than the one I entered in the app.

If the limitations are specific to the Nano S, can it be implemented on the Nano S plus or X which have more memory?

**Comment by ypopovych** [comment]
already fixing in the new UI.
